version: '3'
services:
  # client:
  #   build:
  #     dockerfile: .
  #     context: .
  #   volumes:
  #     - ".:/go/src"
  #   networks:
  #     - seeds
  #   environment:
  #     - "SEED_seeder=seeder:6399"
  #   depends_on:
  #     - seeder

  seeder:
    image: golang:latest
    deploy:
      replicas: 3
    volumes:
      - "cacher:/go/src"
    command: "go run node.go"
    working_dir: "/go/src"
    networks:
      - seeds
      - gossip
    environment:
      - "PORT=6399"
      - "CLUSTER_PORT=7000"

  request_handler:
    image: golang:latest
    volumes:
      - "cacher:/go/src"
    deploy:
      replicas: 3
    working_dir: "/go/src"
    command: "go run request_handler.go"
    depends_on:
      - seeder
    networks:
      - seeds
      - gossip

  child:
    image: golang:latest
    deploy:
      replicas: 3
    volumes:
      - "cacher:/go/src"
    command: "go run node.go"
    working_dir: "/go/src"
    networks:
      - gossip
    environment:
      - "SEEDER_PORT=7000"
      - "SEEDER_NAME=seeder"
    depends_on:
      - seeder

networks:
  seeds:
  gossip:

volumes:
  cacher:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/ehsanfazeli/Projects/distributed-cache